### ISSUE TITLE
npm audit: SEVERE WARNING

### ISSUE THREAD

**Issue by Lod3** [PACKED-vzw/CultURIze#14]
The application uses a method in auth.ts  on line 90 ("did-get-redirect-request",....) which is not supported anymore in the new version of Electron. A replacement method needs to be implemented which the new version of electron supports. 
To replicate the issue run npm install. 
To temporary fix the issues npm audit fix is enough, but this is not a future-proof solution.

**Comment by nvanderperren** [comment]
closed by #45
