### ISSUE TITLE
`users.get()` is deprecated, use `users.getAuthenticated()` 

### ISSUE THREAD

**Issue by Lod3** [PACKED-vzw/CultURIze#16]
Full message: 
DEPRECATED (@octokit/rest): `users.get()` is deprecated, use `users.getAuthenticated()`
File: User.ts, line 22.

> export function getUserInfo(token: string): Promise<User>{
    octokit.authenticate({
        type: "oauth",
        token: token
    })
    return new Promise<User>((resolve,reject)=> {
        octokit.users.get({})
        .then((result: any) =>{
           const userName: string = result.data.login
           const avatar_url: string = result.data.avatar_url
           let newUser: User = new User(token, userName, avatar_url)
           resolve(newUser)
        })
        .catch((error: any) => {
            log.error(`Failed to retrieve user information from GitHub. ${error}`)
            reject("Failed to retrieve user information from GitHub")
        })
    })
}

**Comment by Lod3** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [`users.get()` is deprecated, use `users.getAuthenticated()`](https://trello.com/c/Qwr8aXLP/5-usersget-is-deprecated-use-usersgetauthenticated)

**Comment by nvanderperren** [comment]
closed by #45
