### ISSUE TITLE
Move configuration to config/ folder instead of src/ folder

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/CultURIze#17]
Currently, the instructions state:

> Navigate to the CultURIze folder in your file explorer, **go to src** and locate culturize.conf.example.ts, duplicate this file and remove the .example. You should now have 2 files culturize.conf.example.ts and culturize.conf.ts. Open culturize.conf.ts with your favorite editor and locate theses 2 lines:

The source folder contains the source code of the application. Generally, it should be off limits to changes in a local installation. Why? Updates and upgrades of the application through `git pull` or via third-party package managers (if any such are used).

Locally changed / changeable files should be stored in a separate folder. This entails anything that is related to configuration. Many frameworks will go with a separate `config` folder which is a sibling to the `src` folder, next to such folders as `cache`, `assets`, `logs` or other folders. This way, the `src` folder only contains application logic and nothing else.

**Comment by nvanderperren** [comment]
in the next release, users don't need to change the config file, so this issue won't be fixed.
