### ISSUE TITLE
Configuration needs to be more userfriendly

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/CultURIze#18]
Currently, configuration is done in the `culturize.conf.example.ts` file. The file is unwiedly since it's in typescript and contains a bunch of TS classes.

Per the manual: 

> You should now have 2 files culturize.conf.example.ts and culturize.conf.ts. Open culturize.conf.ts with your favorite editor and locate theses 2 lines:

I'm met with some 170 lines of code which I can easily change. It's unclear to me what I can or can't configure, or what the correct syntax is (let's suppose I'm not a Typescript/Javascript user). So, this isn't a friendly experience for onboarding a new user.

Instead, use a something like [config](https://www.npmjs.com/package/config) to isolate relevant configuration parameters in a separate JSON file which can be stored away from the main code.

**Comment by nvanderperren** [comment]
closed by #45
