### ISSUE TITLE
The "publish" button doesn't work

### ISSUE THREAD

**Issue by netsensei** [PACKED-vzw/CultURIze#19]
I've created a CSV file with a single entry and two columns: "PID" and "URL". I've set up the application and I've created an OAuth key pair. I also created a new repository on Github.  However, when I fill out the form in the application, nothing happens.

** Steps to reproduce **

1. Download the application with `git clone``
2. Do an `npm install` to get all the dependencies
3. Creat an OAuth key pair per the README instructions.
4. Configure the application
5. Open up the application, login with my Github account.

Now I'm ready to fill out the application

1. Create an empty Github repository with the same Github account called "culturize"
2. Create a CSV file with this as content:
```
PID,URL
300,http://google.be/etes
```
3. Go to the application and enter these details in the form:
CSV File Path = path-to-CSV-file
Subdirectory = test (or empty, doesn't matter)
Push the changes to = culturize (Github repo)
4. Hit the publish button.... and notice how nothing happens.
5. Go to Github: nothing was committed to the Github repo either.

** Expected behaviour**

* I would expect an error message, a validation message, a confirmation,... anything. 
* I would expect a convert .htaccess file in my Github repository.

** Additional information**

Since documentation needs to be expanded, it's totally unclear to me what I'm doing wrong or even if I'm doing anything wrong.

**Comment by Lod3** [comment]
Are you on the right branch? 
The latest branch is issues_improvements git checkout issues_improvements before anything for the time being (until we merge the previously mentioned branch is merged with master)

**Comment by netsensei** [comment]
No. I'm not. Neither should I. The README states:

> Fork the Repo on GitHub, and clone it on your local machine.

Which implicitly assumes I'm working on the `master` branch, and that this branch contains a stable version of the application.

As a regular FOSS user, I expect the `master` branch either to contain stable, working code, unless otherwise indicated in a README. Or a clear indication that the code on `master` is failing through functional tests in Travis CI and a "build:failing" badge. In which case I wouldn't spend time trying to setup the application.

To me, It's equally unclear what the branch "issues_improvements" contains, whether it will work, or how the development in that branch is governed. See: https://guides.github.com/introduction/flow/

> Because of this, it's extremely important that your new branch is created off of master when working on a feature or a fix. Your branch name should be descriptive (e.g., refactor-authentication, user-content-cache-key, make-retina-avatars), so that others can see what is being worked on.

Right now, I count no less than 8 different branches - including master - which contain different states. The `development`  branch was last changed on July 25th, 2018 even. I don't think you can reasonably expect users to guess which branch contains the most stable / recent version of the application.

To my mind, there's a gap in the development process of the project: How code is continuously tested and accepted as development progresses while users download and user the application. And how the project communicates in terms of expectation management towards users: which parts (branches) contain WIP code and may be broken, and which parts are "stable" and are tested.

I would suggest discussing how you're going to govern development workflows and processes. How are you going to handle WIP code? How are you going to test fixes and improvements? How are you going to ensure that integrations don't break a branch that people expect to be stable?

**Comment by maxcmoi89** [comment]
The master branch should be stable. What OS are you using ? Could you provide the log file located at : ~/.config/culturizeapp/log.log

**Comment by nvanderperren** [comment]
@netsensei did you enter a URL to the repository or just the name of the repository? I don't encounter your issue.
