### ISSUE TITLE
error starting culturize app

### ISSUE THREAD

**Issue by bert-packed** [PACKED-vzw/CultURIze#22]
Hi,

installed the culturize app following the tutorial, but when starting the application this error appears:
npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! culturizeapp@1.0.0 build: `tsc`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the culturizeapp@1.0.0 build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the culturizeapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs culturizeapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls culturizeapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/bert/CultURIze/npm-debug.log

npm ERR! Linux 4.15.0-47-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! culturizeapp@1.0.0 start: `npm run build && electron ./dist/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the culturizeapp@1.0.0 start script 'npm run build && electron ./dist/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the culturizeapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && electron ./dist/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs culturizeapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls culturizeapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:

/CultURIze/npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle culturizeapp@1.0.0~prestart: culturizeapp@1.0.0
6 silly lifecycle culturizeapp@1.0.0~prestart: no script for prestart, continuing
7 info lifecycle culturizeapp@1.0.0~start: culturizeapp@1.0.0
8 verbose lifecycle culturizeapp@1.0.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle culturizeapp@1.0.0~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/bert/CultURIze/node_modules/.bin:/home/bert/bin:/home/bert/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
10 verbose lifecycle culturizeapp@1.0.0~start: CWD: /home/bert/CultURIze
11 silly lifecycle culturizeapp@1.0.0~start: Args: [ '-c', 'npm run build && electron ./dist/main.js' ]
12 silly lifecycle culturizeapp@1.0.0~start: Returned: code: 1  signal: null
13 info lifecycle culturizeapp@1.0.0~start: Failed to exec start script
14 verbose stack Error: culturizeapp@1.0.0 start: `npm run build && electron ./dist/main.js`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at EventEmitter.emit (events.js:214:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:126:13)
14 verbose stack     at ChildProcess.emit (events.js:214:7)
14 verbose stack     at maybeClose (internal/child_process.js:925:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
15 verbose pkgid culturizeapp@1.0.0
16 verbose cwd /home/bert/CultURIze
17 error Linux 4.15.0-47-generic
18 error argv "/usr/bin/node" "/usr/bin/npm" "start"
19 error node v8.10.0
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error culturizeapp@1.0.0 start: `npm run build && electron ./dist/main.js`
22 error Exit status 1
23 error Failed at the culturizeapp@1.0.0 start script 'npm run build && electron ./dist/main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the culturizeapp package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     npm run build && electron ./dist/main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs culturizeapp
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls culturizeapp
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by Lod3** [comment]
Similar problem, fresh install of node.js and npm
`npm start

> culturizeapp@1.0.0 start /home/lode/CultURIze
> npm run build && electron ./dist/main.js


> culturizeapp@1.0.0 build /home/lode/CultURIze
> tsc

sh: 1: tsc: not found

npm ERR! Linux 4.18.0-17-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! culturizeapp@1.0.0 build: `tsc`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the culturizeapp@1.0.0 build script 'tsc'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the culturizeapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     tsc
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs culturizeapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls culturizeapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lode/CultURIze/npm-debug.log

npm ERR! Linux 4.18.0-17-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! culturizeapp@1.0.0 start: `npm run build && electron ./dist/main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the culturizeapp@1.0.0 start script 'npm run build && electron ./dist/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the culturizeapp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build && electron ./dist/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs culturizeapp
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls culturizeapp
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/lode/CultURIze/npm-debug.log
`

**Comment by Lod3** [comment]
You need to make sure you have the latest version of nodejs and npm, install nodejs and npm from the NodeSource repository. More details here: https://linuxize.com/post/how-to-install-node-js-on-ubuntu-18.04/#install-node-js-from-the-nodesource-repository 
Run `npm install` followed by `npm start`
