### ISSUE TITLE
Change destination argument to destination directory instead of destination filepath

### ISSUE THREAD

**Issue by maartends** [PACKED-vzw/CultURIze#46]
Currently, de `dest` argument us used as a full file path ("target file location"). This needs to be changed to a destination directory (eg.: "destination directory") where the conf-files with their respective names are to be saved.

https://github.com/PACKED-vzw/CultURIze/blob/65f44cbd9807626b5e32c3177ac2391cedcc5d74/culturize.py#L17-L18

https://github.com/PACKED-vzw/CultURIze/blob/65f44cbd9807626b5e32c3177ac2391cedcc5d74/culturize.py#L82-L83

**Comment by nvanderperren** [comment]
closed by #47
