### ISSUE TITLE
More explanation needed with nginx setup 

### ISSUE THREAD

**Issue by brechtvdv** [PACKED-vzw/CultURIze#60]
When setting up the nginx settup (in the crontab setup) you need to add following line in your nginx config:
```
    include /etc/nginx/culturize/one_nginx.conf;
```

I guess you need to adapt `one_nginx.conf` to the correct file in your htaccess repo and repeat that for every subdirectory?
In my case, I changed it to this:`
```
    include /etc/nginx/culturize/test/nginx_redirect.conf;
```

If this is the correct approach, can you update the README to clarify this?

**Comment by douwedb** [comment]
Hi Brecht,

Thanks for reporting. You're correct. I've updated this in the wiki: https://github.com/PACKED-vzw/CultURIze/wiki/Culturize-&-Crontab

Please reopen if you think the description is not clear enough or if it's still missing in another place.
